/** رموز الخادم الثابتة ← عربية بسيطة. الرمز يصل في الحقل code كما هو (app/core/errors.py). */
const AR: Record<string, string> = {
  access_expired: "انتهت الجلسة. سجّل الدخول من جديد.",
  account_disabled: "هذا الحساب موقوف.",
  actor_missing: "تعذّر التعرّف على المستخدم. سجّل الدخول من جديد.",
  already_registered: "هذا الرقم مسجَّل من قبل.",
  area_overlap: "المنطقة تتداخل مع منطقة أخرى برسم مختلف.",
  area_polygon_invalid: "حدود المنطقة غير صحيحة. ارسم ثلاث نقاط على الأقل داخل الخريطة.",
  batch_departure_requires_notice: "أرسل إشعار الدفعة قبل الانطلاق.",
  batch_empty: "الدفعة فارغة.",
  batch_qty_exceeds_collected: "الكمية أكبر مما جُمع.",
  branch_delete_forbidden: "لا يُحذف فرع له طلبيات.",
  branch_missing: "الفرع غير موجود.",
  branch_not_approved: "الفرع لم يُعتمد بعد.",
  branch_required: "اختر الفرع.",
  by_invalid: "طريقة التجميع غير معروفة.",
  category_not_found: "التصنيف غير موجود.",
  channels_order_incomplete: "رتّب القنوات الثلاث كلها.",
  custody_already_decided: "تقرّر مصير هذه الأمانة من قبل.",
  custody_exceeds_target_qty: "الكمية أكبر مما تحتاجه الطلبية المختارة.",
  custody_open: "لدى السائق أمانة لم يتقرّر مصيرها بعد.",
  custody_target_lacks_item: "الطلبية المختارة لا تحتوي هذا الصنف.",
  custody_target_not_plannable: "الطلبية المختارة لا تقبل إضافة استلام الآن.",
  custody_warehouse_invalid: "اختر مخزناً صحيحاً.",
  customer_not_found: "العميل غير موجود.",
  derived_field_write: "هذه القيمة تُحسب تلقائياً ولا تُكتب يدوياً.",
  dispute_already_resolved: "حُسم هذا النزاع من قبل.",
  dispute_cash_refund_driver: "الاسترداد النقدي يمرّ عبر السائق المسند.",
  dispute_loss_party: "حدّد من يتحمّل الخسارة.",
  dispute_money_needs_decision: "حدّد القرار المالي قبل الحسم.",
  dispute_not_found: "النزاع غير موجود.",
  driver_cash_cap_exceeded: "تجاوز السائق سقف الكاش المسموح.",
  driver_city_mismatch: "السائق من مدينة أخرى.",
  driver_missing: "اختر سائقاً.",
  forbidden_branch: "لا صلاحية لك على هذا الفرع.",
  forbidden_grant: "لا تملك منح هذه الصلاحية.",
  forbidden_handover: "لا يمكن تسليم هذا المبلغ.",
  forbidden_not_member: "لست عضواً في هذه اللوحة.",
  forbidden_owner_member: "لا يُعدَّل حساب المالك.",
  forbidden_owner_only: "هذا الإجراء للمالك وحده.",
  forbidden_permission: "لا تملك صلاحية هذا القسم.",
  forbidden_role: "لا صلاحية لك هنا.",
  forbidden_self_edit: "لا تعدّل صلاحياتك بنفسك.",
  handover_exceeds_cash: "المبلغ أكبر مما يحمله السائق.",
  intake_needs_qty_and_cost: "اكتب الكمية والتكلفة.",
  invalid_transition: "لا يمكن نقل الطلبية إلى هذه الحالة الآن.",
  item_below_cost: "سعر البيع أقل من التكلفة المرجعية.",
  item_cost_missing: "الصنف بلا تكلفة مكتوبة، فلا يُعرض للبيع.",
  item_not_found: "الصنف غير موجود.",
  item_not_orderable: "الصنف غير متاح للطلب.",
  ledger_unbalanced: "القيد غير متوازن.",
  line_not_found: "السطر غير موجود.",
  location_missing: "حدّد الموقع.",
  login_failed: "رقم الهاتف أو كلمة المرور غير صحيحة.",
  login_locked: "محاولات كثيرة. انتظر قليلاً ثم أعد المحاولة.",
  margin_without_source: "لا مصدر لهذا الصنف يُحسب منه الهامش.",
  min_order_amount: "الطلبية أقل من الحد الأدنى.",
  min_order_lines: "عدد الأصناف أقل من الحد الأدنى.",
  missing_setting: "إعداد مطلوب لم يُحدَّد بعد.",
  money_precision: "المبلغ بثلاث خانات عشرية على الأكثر.",
  money_range: "المبلغ خارج الحد المسموح.",
  no_driver: "لا سائق متاح.",
  not_invited: "هذا الرقم غير مدعو إلى اللوحة.",
  not_pending: "الطلب ليس بانتظار الاعتماد.",
  not_registered: "هذا الرقم غير مسجَّل.",
  offer_already_decided: "تقرّر هذا العرض من قبل.",
  offer_not_found: "العرض غير موجود.",
  offset_exceeds: "المبلغ أكبر من المستحق.",
  order_empty: "الطلبية فارغة.",
  order_locked: "الطلبية مقفلة للتعديل.",
  order_not_found: "الطلبية غير موجودة.",
  otp_already_used: "استُعمل هذا الرمز من قبل.",
  otp_channel_unavailable: "تعذّر إرسال الرمز الآن. أعد المحاولة بعد قليل.",
  otp_expired: "انتهت صلاحية الرمز. اطلب رمزاً جديداً.",
  otp_invalid: "الرمز غير صحيح.",
  otp_too_soon: "انتظر قليلاً قبل طلب رمز جديد.",
  owner_confirmation_required: "يحتاج هذا تأكيد المالك.",
  party_not_approved: "الطرف لم يُعتمد بعد.",
  password_change_required: "غيّر كلمة المرور المؤقتة أولاً.",
  pay_method_not_offset: "طريقة الدفع لهذا السائق ليست المقاصّة.",
  pay_method_not_periodic: "طريقة الدفع لهذا السائق ليست الدورية.",
  payout_exceeds_payable: "المبلغ أكبر من مستحق المورد.",
  payout_exceeds_wallet: "المبلغ أكبر من رصيد السائق.",
  pickup_code_mismatch: "رمز الاستلام غير مطابق.",
  pickup_proof_required: "إثبات الاستلام مطلوب.",
  plan_incomplete: "مخطط الاستلام لا يغطي كل الكميات.",
  plan_locked: "المخطط مقفل بعد بدء التجميع.",
  qty_exceeds_available: "الكمية أكبر من المتاح.",
  qty_precision: "الكمية بثلاث خانات عشرية على الأكثر.",
  qty_range: "الكمية خارج الحد المسموح.",
  refund_exceeds_driver_cash: "الاسترداد أكبر مما يحمله السائق.",
  sms_must_be_last: "الرسالة النصية تبقى آخر قناة.",
  source_required: "اختر مصدراً.",
  stock_negative: "الرصيد في المخزن لا يكفي.",
  stop_locked: "نقطة الاستلام مقفلة.",
  stop_not_found: "نقطة الاستلام غير موجودة.",
  supplier_not_found: "المورد غير موجود.",
  ticket_invalid: "انتهت الخطوة. ابدأ من جديد.",
  token_invalid: "انتهت الجلسة. سجّل الدخول من جديد.",
  transfer_needs_qty_and_target: "اكتب الكمية والمخزن المستلم.",
  unauthenticated: "سجّل الدخول أولاً.",
  unit_mismatch: "الوحدة غير مطابقة.",
  user_not_found: "المستخدم غير موجود.",
  withdrawal_exceeds_treasury: "المبلغ أكبر مما في الخزينة.",
  wrong_audience: "هذا الحساب لا يدخل هذه الواجهة.",
  zone_conflict: "الفرع يقع في منطقتين برسمين مختلفين.",
  zone_inactive: "منطقة التوصيل موقوفة.",
  zone_missing: "الفرع خارج مناطق التوصيل.",
  phone_invalid: "اكتب رقماً ليبياً صحيحاً، مثل 091 000 0001.",
  dispute_open_per_item: "لهذا الصنف بلاغ مفتوح بالفعل.",
  list_name_per_branch: "الاسم مستعمل لقائمة أخرى في هذا الفرع.",
  list_has_unavailable: "في القائمة صنف غير متاح الآن.",
  list_not_found: "القائمة غير موجودة.",
  member_exists: "هذا الرقم عضو في منشأة من قبل.",
  establishment_exists: "سجّلت منشأتك من قبل.",
  supplier_exists: "سجّلت محلّك من قبل.",
  no_establishment: "أكمل بيانات منشأتك أولاً.",
  no_supplier: "أكمل بيانات محلّك أولاً.",
  media_type_unsupported: "الملف ليس صورة أو PDF.",
  media_empty: "الملف فارغ.",
  media_too_large: "الملف أكبر من 10 ميغابايت.",
  media_purpose_unknown: "نوع الملف غير معروف.",
  media_not_owned: "لا يُستعمل ملف رفعه غيرك.",
  media_not_found: "الملف غير موجود.",
  month_invalid: "الشهر غير صحيح.",
  location_in_use: "لا يُعطَّل موقع عليه عروض نشطة. أوقف عروضه أولاً.",
  location_not_found: "الموقع غير موجود.",
  payout_not_found: "الدفعة غير موجودة.",
  reminder_invalid: "اختر يوماً ووقتاً للتذكير.",
  supplier_may_only_propose: "تقترح الصنف، ويعتمده مَدَد.",
  offer_on_proposed_product: "العرض على صنف مقترح يبقى موقوفاً حتى يعتمده مَدَد.",
  offer_identity_immutable: "الصنف والوحدة والموقع لا تتغير بعد إضافة العرض. أضف عرضاً جديداً.",
  order_locked_for_customer: "أكّد مَدَد الطلبية؛ التعديل عبر مَدَد الآن.",
  item_not_orderable_at_place: "صنف في السلة لم يعد متاحاً.",
  order_awaiting_owner: "السلة بانتظار تأكيد صاحب المنشأة.",
  network: "تعذّر الاتصال بالخادم. تحقق من اتصالك ثم أعد المحاولة.",
  server: "حدث خطأ في الخادم. أعد المحاولة بعد قليل.",
  validation: "بعض الحقول غير صحيحة.",
};

export function arabicError(code: string): string {
  return AR[code] ?? `تعذّر إتمام العملية (${code}).`;
}
